### ISSUE TITLE
Cannot find module './function/ql'

### ISSUE THREAD

**Issue by kanvenzeng** [smiek2121/scripts#53]
🔔3.3~3.18 约惠女王节 嗨购不停, 开始!

====================共2个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2022/3/8 14:37:51=====================

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './function/ql'
Require stack:
- /ql/scripts/smiek2121_scripts/sendNotify.js
- /ql/scripts/smiek2121_scripts/gua_opencard115.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/ql/scripts/smiek2121_scripts/sendNotify.js:133:5)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/ql/scripts/smiek2121_scripts/sendNotify.js',
    '/ql/scripts/smiek2121_scripts/gua_opencard115.js'
  ]
}

Node.js v17.5.0

青龙版本是2.11.3，请问是缺少哪个依赖？谢谢！

**Comment by chiupam** [comment]
@kanvenzeng 您的 smiek2121_scripts 目录中没有 sendNotify.js 这个文件
您的 smiek2121_scripts 目录中没有 gua_opencard115.js 这个文件

**Comment by kanvenzeng** [comment]
@chiupam  都是直接拉库的，怎么会缺少这两个文件？请问怎样补上这两个文件？谢谢！

**Comment by chiupam** [comment]
@kanvenzeng 最简单的方法是使用ql raw这两个文件的链接然后拉进去 我估计是你的ql repo命令黑名单设置了过滤 修改ql repo的命令是最好的

**Comment by kanvenzeng** [comment]
@chiupam  ql repo https://github.com/smiek2121/scripts.git "jd_|gua_" "" "ZooFaker_Necklace.js|JDJRValidator_Pure.js|sign_graphics_validate.js|cleancart_activity.js|jdCookie.js|sendNotify.js"

这样拉对吗？请问要怎样修改ql repo命令？谢谢！

**Comment by chiupam** [comment]
@kanvenzeng ql repo https://github.com/smiek2121/scripts.git "jd_|gua_" "" "ZooFaker_Necklace.js|JDJRValidator_Pure.js|sign_graphics_validate.js|cleancart_activity.js|jdCookie.js" 

这样就可以拉取sendNotify.js了 gua_这个可能是库那边更新比较慢 你没拉成功而已

**Comment by kanvenzeng** [comment]
@chiupam 应该不是缺sendNotify.js和gua_opencard115.js的问题，我删除smiek2121_scripts目录重新拉库，smiek2121_scripts目录下面是有那两个文件，但依旧出现上面的错误。

**Comment by smiek2121** [comment]
@kanvenzeng 你哪里有用到”function/ql” 文件
看你用谁的脚本 提示缺少 “function/ql”

**Comment by kanvenzeng** [comment]
我就是用smiek大佬的库啊，“3.3~3.18 约惠女王节 嗨购不停”这个脚本。

**Comment by smiek2121** [comment]
@kanvenzeng 是你哪有用“function/ql”
跟这脚本没关系

**Comment by kanvenzeng** [comment]
@smiek2121  我怎样查找我哪里用了“function/ql”？

**Comment by smiek2121** [comment]
@kanvenzeng 你先看scripts下哪个文件夹中有 function 中有ql的
不然就只能一个一个文件看了
看你拉谁的库 去问问作者

**Comment by kanvenzeng** [comment]
6dylan6_jdpro的脚本库下面有function，但里面什么也没有的。

**Comment by smiek2121** [comment]
@kanvenzeng 看是哪个库 去问谁
我不知道哪个脚本的问题

**Comment by kanvenzeng** [comment]
说得我都蒙了，我就是拉了你和6dylan6的库啊，运行你的“.3~3.18 约惠女王节 嗨购不停”脚本报错的。

**Comment by smiek2121** [comment]
@kanvenzeng 是啊 我库里的文件都没有你这个提示错误的信息内容
我也不知道你为什么会有这个错误啊

**Comment by ALixuhui** [comment]
原因：未知；
解决方法：
![image](https://user-images.githubusercontent.com/40882157/157358687-77211402-2ae4-40a5-9163-7df39d04fd13.png)

就可以跑起来了；

**Comment by lamking** [comment]
> 原因：未知； 解决方法： ![image](https://user-images.githubusercontent.com/40882157/157358687-77211402-2ae4-40a5-9163-7df39d04fd13.png)
> 
> 就可以跑起来了；

感谢

**Comment by kanvenzeng** [comment]
@ALixuhui  我昨天查看过6dylan6_jdpro的function目录，里面是空的，没有文件。晚上回去再确认下，如果是空目录，又是哪里出问题呢？谢谢！

**Comment by ALixuhui** [comment]
> @ALixuhui 我昨天看过6dylan6_jdpro哪里的function目录，里面是空的，没有文件。晚上回去再确认下，如果是空目录，又是出问题呢？谢谢！
如果是空的，有理由怀疑6dylan6_jdpro 的库没拉全，可以再拉一遍；

**Comment by kanvenzeng** [comment]
@ALixuhui  是重新运行一次拉库的任务吗？还是要删除所有的任务和脚本，然后再运行拉库任务？

**Comment by ilaotan** [comment]
找个sendNotify.js 放到对应位置 /ql/scripts/smiek2121_scripts/sendNotify.js  不要瞎回复占用频道资源了,多大点事

**Comment by kanvenzeng** [comment]
@ilaotan  smiek2121_scripts目录本原就有sendNotify.js这个文件了。是否用其它的覆盖它？

**Comment by kanvenzeng** [comment]
> 原因：未知； 解决方法： ![image](https://user-images.githubusercontent.com/40882157/157358687-77211402-2ae4-40a5-9163-7df39d04fd13.png)
> 
> 就可以跑起来了；

感谢大佬！
